ALTER TABLE BUS_EXPENDITURE ADD BDX varchar(50) NULL;
ALTER TABLE BUS_EXPENDITURE ADD BDY varchar(50);
ALTER TABLE BUS_EXPENDITURE ADD BDADDRESS nvarchar(200);
ALTER TABLE BUS_EXPENDITURE ADD PHOTO1 nvarchar(100);
ALTER TABLE BASE_PACKAGE ADD PAYTYPE integer NOT NULL DEFAULT(1);
